services:
  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - '3000:3000'
    depends_on:
      - goobs
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - goobs-network

  goobs:
    build: .
    container_name: goobs
    ports:
      - '8080:8080'
    networks:
      - goobs-network

networks:
  goobs-network:
    name: goobs-network
    # external: true
