.PHONY: run
run:
	docker compose -p goobs -f docker-compose.yml up --build --force-recreate

.PHONY: run-grafana
run-grafana:
	docker compose -p goobs -f docker-compose.yml up grafana --build --force-recreate