syntax = "proto3";

option go_package = "github.com/av-ugolkov/backend-examples/go/protobuf/gen";

message Request {
    string label = 1;
}

message Point {
    int32 x = 1;
    int32 y = 2;
    string label = 3;
}

message Line {
    Point start = 1;
    Point end = 2;
    string label = 3;
}

message Polyline {
    repeated Point point = 1;
    string label = 2;
}

service Data {
    rpc GetPoint(Request) returns (Point);
    rpc GetLine(Request) returns (Line);
    rpc GetPolyline(Request) returns (Polyline);
}