apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp-dep
  labels:
    app: goapp
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - name: web
        image: app:v1
        imagePullPolicy: Never
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 5858
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: goapp-svc
spec:
  selector:
    app: goapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5858
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: goapp-ingress
spec:
  rules:
    - host: mini.service.test
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: goapp-svc
                port:
                  number: 80