.PHONY: help
help:
	go run . --help

.PHONY: h
h:
	go run . -h

.PHONY: helpf
helpf:
	go run . help flags

.PHONY: run
run:
	go run . flags --boolean --number 27 --string "A string." Other things. And more

.PHONY: r
r:
	go run . flags -b -n 27 -s "A string." Other things. And more