apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
apiVersion: srv/v1
kind: Deployment
metadata:
  name: wow-srv
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wow-srv
  template:
    metadata:
      labels:
        app: wow-srv
    spec:
      containers:
        - name: wow-srv
          image: 