apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: srv/v1
kind: Deployment
metadata:
  name: wow-srv
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wow-srv
  template:
    metadata:
      labels:
        app: wow-srv
    spec:
      containers:
        - name: wow-srv
          image: wow-server:v1
          ports:
            - containerPort: 5555
---
apiVersion: v1
kind: Service
metadata:
  name: wow-srv-svc
  namespace: dev
spec:
  selector:
    app: wow-srv
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5555